export enum TableStatusEnum {
    FROZEN_UNOCCUPIED = "FROZEN_UNOCCUPIED",
    FROZEN_ALLOCATED = "FROZEN_ALLOCATED",
    FROZEN_OCCUPIED = "FROZEN_OCCUPIED",
    UNFROZEN_UNOCCUPIED = "UNFROZEN_UNOCCUPIED",
    UNFROZEN_ALLOCATED = "UNFROZEN_ALLOCATED",
    UNFROZEN_OCCUPIED = "UNFROZEN_OCCUPIED"
}
